name: Integration tests

on: push

jobs:
  docker-compose:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: composer install --no-interaction
      - run: docker-compose --file tests/docker-compose.yml run tests
