name: Integration tests

on: push

jobs:
  docker-compose:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
      - run: composer install --no-interaction
      - run: docker-compose --file tests/docker-compose.yml run tests
