name: Main tests

on: push

jobs:
  tests:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        php-versions: ['7.4', '8.1', '8.2']
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
      - run: script/test
